language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-16

env:
  global:
    ADB_INSTALL_TIMEOUT=6

before_install:
  - script/accept_constraintlayout_license_workaround

before_script:
  - script/run_emulator

after_success:
  - script/upload_coverage_codecov
  - script/upload_coverage_coveralls

after_script:
  - adb logcat -d
